package strings;

import java.util.ArrayList;
import java.util.List;

/**
 * Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is
 * generated by deleting some character of a given string without changing its order.
 * Input : abc
 * Output : a, b, c, ab, bc, ac, abc
 */
public class _6_PrintAllSubsequence {

    static List<String> result = new ArrayList<>();

    public static void main(String[] args)
    {
        String str = "abc";
        findSubSequences(str, "");
        System.out.println(result);
    }

    //TC is O(2^n)
    //SC is O(1)
    private static void findSubSequences(String str, String ans)
    {
        if (str.length() == 0) {
            result.add(ans);
            return;
        }

        // pick the first char for result
        findSubSequences(str.substring(1), ans + str.charAt(0));

        // don't pick the first char for result
        findSubSequences(str.substring(1), ans);
    }
}
